DATASET:
  NAME: "Neymar"
DATALOADER:
  TYPE: "LOCAL"
  KEY: ""
  SECRET: ""
  KEYWORDS: ["Neymar"]
  COUNT: 20
  MINSIZE: 1000
  MAXSIZE: 1600
PROCESS:
  BBOX: "yes"
  RESIZE: "yes"
  POSE_ESTIMATION: "yes"
  DENSEPOSE: "yes"
  ORDER: ["loader","bbox","densepose","pose_estimation","resize"]
BBOX:
  VIS_PRED: "no"
  TRESH: 2.0
  MIN_SIZE_HEIGTH: 2
  MIN_SIZE_WIDTH: 15
  PATH_PROCESS: "raw"
  ONLY_ONE: "yes"
  SAVE_PRED: "yes"
RESIZE:
  SIZE: "500x500"
  INTERPOLATION: 2
  PATH_PROCESS: "pose_estimation/bbox_raw/other"
POSE_ESTIMATION:
  VIS_PRED: "no"
  TRESH: 0.4
  PATH_PROCESS: "bbox/raw"
  ONLY_ONE: "yes"
  SAVE_RGB: "yes"
  SAVE_BLACK: "yes"
  SAVE_OTHER: "yes"
  PATH_OTHER: "/home/pc/Documents/Path_containing_images_with_same_name_as_input/"
  DRAW_THICKNESS_LINES: 2
  DRAW_THICKNESS_POINTS: 0
  MODEL: 136
DENSEPOSE:
  PATH_PROCESS: "bbox/raw"
  ONLY_ONE: "yes"
  SAVE_BLACK: "yes"
  SAVE_RGB: "yes"
  SAVE_GREEN: "yes"
  TRESH: 0.7
  
 

  
 
  
