DATASET:
  NAME: "1-Foot" # Name of the general folder.
DATALOADER:
  TYPE: "FLICKR" # Available are FLICKR or LOCAL. If local, images have to be in DATASET.NAME/raw/
  KEY: "key" # personal flickr key
  SECRET: "secret"  # personal flickr secret
  KEYWORDS: ["Neymar","Ronaldo"] # keyword list for flickr search
  COUNT: 10 # Number of images to download
  MINSIZE: 1000 #  Size of images to download
  MAXSIZE: 1600 # available size on flickr: [4096,3072,2048,1600,1024,800,640,400,320,240,100]
PROCESS:
  BBOX: "yes"
  RESIZE: "yes"
  POSE_ESTIMATION: "yes"
  ORDER: ["loader","bbox","resize","pose_estimation"] # Order in which the tasks are carried out
BBOX:
  VIS_PRED: "yes" # save Alphapose prediction visualisation
  TRESH: 2.5 # bad score value is below 2 and good score valur is above 2.5 in general with alphapose
  MIN_SIZE: 30 # Minimum size of the bbox compare to the input image in percentage
  PATH_PROCESS: "raw"
  ONLY_ONE: "no" # extract only one box of the image
  SAVE_PRED: "yes" # save extracted box
RESIZE:
  SIZE: "500x500" #new_width x new_heigth
  INTERPOLATION: 2 # 0=cv2.INTER_NEAREST, 1=cv2.INTER_LINEAR, 2=cv2.INTER_CUBIC, 3=cv2.INTER_AREA, 4=cv2.INTER_LANCZOS4
  PATH_PROCESS: "bbox/raw" # specifie which images to resize
POSE_ESTIMATION:
  VIS_PRED: "yes"
  TRESH: 0.4
  PATH_PROCESS: "resize/bbox_raw"
  ONLY_ONE: "no"
  SAVE_RGB: "yes" 
  SAVE_BLACK: "yes"
  SAVE_OTHER: "no"
  PATH_OTHER: "/home/pc/Documents/Path_containing_other_images_with_same_name_as_input/"
  DRAW_THICKNESS_LINES: 2
  DRAW_THICKNESS_POINTS: 0
  MODEL: 136 # Number of keypoints to detect. 136, 26, 17
 




  
 
  
